name: Market prices - daily

on:
  # 매일 8시 (KST)
  schedule:
    - cron: '0 23 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Cache maven
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/deps.edn') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-
          
    - run: clojure -m green.market.daily `date --date='0 day ago' '+%Y-%m-%d'`
      env:
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
